### ISSUE TITLE
Touch Driver Update Help

### ISSUE THREAD

**Issue by spiriz** [jankae/LCR#1]
Im using the same TFT(Base on SSD1289)  but the touch driver has changed to newer version (ADS7843 to XPT2046) 
Can you update the touch library ( im trying to modify the new one but  unsuccessful)  Thank you very much.

**Comment by jankae** [comment]
Hi,
sorry, but I don't think I can be of much help here. I do not have a display with the xpt2046 and also haven't worked on this project for quite some time (I consider it finished). If you manage to get the driver to work, I'd be happy to include it in this project so others can use it, but otherwise I will probably not be able to do anything for you here.

**Comment by spiriz** [comment]
Thank you very much 😍
